name: Initial Java CI

on: [push]

permissions:
  contents: read
  checks: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Download and add JSON library
        run: |
          # Download the JSON library JAR file
          wget -O json-library.jar https://search.maven.org/remotecontent?filepath=org/json/json/20231013/json-20231013.jar
          # Add the library JAR to the classpath
          export CLASSPATH=.:json-library.jar
        working-directory: src/PantryPal

      # Get dependencies
      - name: Install dependencies
        run: bash setup_lib.sh

      # Build everything
      - name: Make
        run: make

      # Run unit test
      - name: Run unit test
        run: make test
